# Generated by Django 5.1.5 on 2026-05-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
