# Generated by Django 5.1.5 on 2026-05-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_clinicmanagerprofile'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctors',
            field=models.ManyToManyField(related_name='treatments', to='accounts.doctorprofile'),
        ),
    ]
