# Generated by Django 5.1.5 on 2026-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_remove_treatment_doctor_treatment_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUIVI', 'En suivi')], default='EN_COURS', max_length=20),
        ),
    ]
